/* Canned API payloads shared by the jsdom render audit and the Chrome
   tip-geometry audit. Shapes mirror the real serializers; the backtest
   payload carries window/per_tier so the audits exercise the full table,
   not the "not run yet" branch (ASSUMPTIONS §54). */
const soon = (h) => new Date(Date.now() + h * 3.6e6).toISOString();
export const PAYLOADS = {
  "/api/upcoming": { model_version: "vp-2026-07-26", predictions: [{
    match_id: "m1", team1_name: "RED", team2_name: "BLU",
    start_ts: soon(2), p_model: 0.61, p_elo: 0.55,
    best_of: 3, event: "VCT Stage 2", low_history: true,
    team1_prior_maps: 2, team2_prior_maps: 1 }] },
  "/api/scoreboard": { graded: [{ match_id: "g1", team1_name: "AAA",
    team2_name: "BBB", start_ts: soon(-24),
    p_model: 0.58, team1_won: 1, model_correct: 1, elo_correct: 0,
    p_elo: 0.51, maps_won_1: 2, maps_won_2: 0, model_version: "vp",
    low_history: false }],
    pending: [{ match_id: "m1", team1_name: "RED", team2_name: "BLU",
      start_ts: soon(2), p_model: 0.61, low_history: false }],
    summary: { n_graded: 18, n_pending: 1, n_scored: 18, n_low_history: 0,
      model: { accuracy: 0.6875, log_loss: 0.5582, brier: 0.19 },
      elo: { accuracy: 0.625, log_loss: 0.5789, brier: 0.2 } } },
  "/api/model": { version: "vp-2026-07-26", trained_at:
    "2026-07-26T09:00:00+00:00", n_train: 5489, features: [] },
  "/api/results": { model: { accuracy: 0.621, log_loss: 0.657,
    brier: 0.226 }, elo: { accuracy: 0.613, log_loss: 0.658, brier: 0.23 },
    series: { model: { accuracy: 0.621, log_loss: 0.657, brier: 0.226 },
    elo: { accuracy: 0.613, log_loss: 0.658, brier: 0.23 } },
    map: { model: { accuracy: 0.59, log_loss: 0.6693, brier: 0.237 },
    elo: { accuracy: 0.588, log_loss: 0.6719, brier: 0.239 } },
    window: "recent" },
  "/api/markets": { generated_at: soon(0), section: "LIVE",
    gate: { n_graded: 3, required: 30, ev_validated: false },
    summary: { n_graded: 3, win_rate: 0.67, beat_close_rate: 0.5 },
    by_tier: {}, by_market: {}, skipped: { n_unpriceable: 0,
      n_group_errors: 0 },
    unit_tracker: { start_ts: "2026-08-08T00:00:00+00:00",
      params: { kelly_fraction: 0.25, notional_units: 100,
        ev_clip: 0.1, stake_cap_units: 3 },
      n_staked: 1, n_wins: 1, units_staked: 0.33, units_pnl: 2.5,
      roi_pct: 750.0, flat_pnl_units: 7.5, provisional: true,
      picks: [{ match_id: "m1", match: "RED vs BLU", selection: "BLU",
        start_ts: soon(-30), price_entry: 8.5, ev_pct: 10.2,
        stake_units: 0.33, pnl_units: 2.5, won: true }] },
    picks: [{ match_id: "m1", market: "series_moneyline", line: null,
      source: "cloudbet", match: "RED vs BLU", event: "VCT Stage 2",
      tier: "tier1", start_ts: soon(2), selection: "BLU", p_model: 0.39,
      price_entry: 2.9, implied: 0.3448, shin: 0.351,
      shin_consensus: 0.351, n_books: 2, multiplicative: 0.348,
      overround: 1.05, ev_pct: 13.1, clv_pct: null, extrapolated: false,
      graded: false, won: null, entry_captured_at: soon(-1),
      entry_kind: "freeze", close_captured: false }] },
  "/api/trends": { generated_at: soon(0),
    params: { window_maps: 10, active_days: 60, min_lifetime_maps: 5 },
    n_teams: 2, teams: [
      { team_id: "t1", name: "Sample Squad", n_lifetime: 42, n_window: 10,
        last_map_ts: soon(-24), win_rate: 0.7, spread_avg: 3.1,
        pistol_wr: 0.6, comb_kills_avg: 128.4, fk_diff12: 1.25,
        method_mix: { elim: 0.72, boom: 0.06, defuse: 0.18, time: 0.04 },
        agents_top: [{ agent: "Jett", n: 9 }, { agent: "Omen", n: 8 }] },
      { team_id: "t2", name: "Other Org", n_lifetime: 12, n_window: 10,
        last_map_ts: soon(-48), win_rate: 0.4, spread_avg: -1.2,
        pistol_wr: null, comb_kills_avg: 131.0, fk_diff12: null,
        method_mix: null, agents_top: [] }] },
  "/api/backtest": { n_predictions: 6800, n_retrains: 97,
    window: { n_predictions: 6800, n_retrains: 97,
      first_prediction: "2024-08-02T14:00:00+00:00",
      last_prediction: "2026-07-22T20:00:00+00:00" },
    per_tier: { tier1: { n_scored: 399, model_acc: 0.569, elo_acc: 0.561,
      model_ll: 0.679, elo_ll: 0.684 } },
    summary: { model_acc: 0.59, elo_acc: 0.588 }, synthetic_data: false },
  "/api/match/m1": { match_id: "m1",
    prediction: { match_id: "m1", start_ts: soon(2), event: "VCT Stage 2",
      series: "Group A", best_of: 3, team1: "t-red", team2: "t-blu",
      team1_name: "RED", team2_name: "BLU", p_model: 0.61, p_elo: 0.55,
      low_history: false, model_version: "vp-2026-07-26",
      maps_dist: { 2: 0.42, 3: 0.58 },
      per_map: { Ascent: 0.63, Bind: 0.59 },
      per_map_elo: { Ascent: 31, Bind: -12 } },
    ledger: { match_id: "m1", start_ts: soon(2), team1: "t-red",
      team2: "t-blu", team1_name: "RED", team2_name: "BLU",
      event: "VCT Stage 2", best_of: 3, p_model: 0.61, p_elo: 0.55,
      model_version: "vp-2026-07-26", low_history: 0, graded: 0,
      team1_won: null, made_at: soon(-3), graded_at: null,
      maps_played: null },
    picks: [{ match_id: "m1", market: "series_moneyline", line: null,
      source: "cloudbet", selection: "BLU", p_model: 0.39,
      price_entry: 2.9, implied: 0.3448, shin: 0.351,
      shin_consensus: 0.351, ev_pct: 13.1, clv_pct: null,
      extrapolated: false, ev_excluded: null, graded: false, won: null }],
    team_history: {
      "t-red": { name: "RED", recent: [{ start_ts: soon(-48),
        event: "VCT Stage 2", opponent: "GRN", won: true, score: "2-1" }] },
      "t-blu": { name: "BLU", recent: [{ start_ts: soon(-72),
        event: "VCT Stage 2", opponent: "YLW", won: false, score: "0-2" }] } },
    placeholder: false },
};
