import React from "react";

export function HowItWorks() {
  return (
    <div className="how">
      <div className="page-head"><h1>How it works</h1></div>
      <div className="panel">
        <div className="panel-title">The idea</div>
        <p>
          vpredict makes win probability calls on professional Valorant
          matches before they start, in public, and keeps score. Every
          number on this site is generated by the system from stored data.
          Nothing is typed in by hand. This page explains the machinery in
          plain language.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">Where the data comes from</div>
        <p>
          A small crawler reads vlr.gg, the community results site. It
          honors their robots.txt, waits at least 1.1 seconds between
          requests, and runs single file. Every fetched page is cached to
          disk, so nothing is downloaded twice. The store reaches back
          about two years and grows as matches finish.
        </p>
        <p>
          Match pages provide the raw material: map scores, attack and
          defense splits, first kills, and pistol rounds. That is what the
          features are built from.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">How predictions are made</div>
        <p>
          For each map, the model looks at the difference between the two
          teams as of that moment: recent round share, attack and defense
          efficiency, first kills, pistol rounds, rest days, roster
          stability, and Elo ratings overall and per map.
        </p>
        <p>
          One rule sits above everything. A feature may only use matches
          that finished before the match being predicted started. The same
          rule applies in training and in serving, and a test suite guards
          it. Per map probabilities are combined across the current map
          pool and pushed through the exact best-of math to produce a
          series probability.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">Training and calibration</div>
        <p>
          Splits are chronological, never shuffled. The model learns on
          the oldest matches, picks its settings on the next slice, and is
          judged once on the newest. Two candidates compete, a regularized
          logistic regression and a gradient boosted model, and validation
          decides which one ships.
        </p>
        <p>
          Calibration then adjusts the raw scores so probabilities mean
          what they say: across many matches called at 60 percent, about
          60 percent should be wins. A tuned Elo baseline is built from
          the same data as the yardstick. Beating it is the bar.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">The freeze rule</div>
        <p>
          The first accepted prediction for a match is the record. To be
          accepted it has to be made at least five minutes before the
          scheduled start. After that, nothing can change it. Not a
          retrain, not a better model, not new information. The scoreboard
          shows what the model said at the time, word for word.
        </p>
        <p>
          Without this rule a prediction site can quietly rewrite its
          history. With it, being wrong stays on the page.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">Grading</div>
        <p>
          When a match finishes, the crawler picks up the result and the
          frozen row is graded. Correct picks is the simple score. Log
          loss and Brier grade the confidence behind each pick, and they
          punish a confident miss much harder than a cautious one. Lower
          is better for both. The Elo baseline is graded at the same
          moments under the same rules.
        </p>
        <p>
          Predictions where either team had fewer than three recorded maps
          stay listed but are not scored. Those calls lean on defaults and
          would only add noise.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">The backtest, and why it stays separate</div>
        <p>
          The backtest replays the full two years of history. It walks
          forward through time, retrains on the production schedule, and
          predicts each match using only what was knowable at that moment.
          It answers one question: what would this system have done.
        </p>
        <p>
          It is still a simulation, computed after the fact. So it never
          mixes with the live scoreboard, which holds only calls made in
          real time before real matches. The full backtest is shown per
          tier, including the stretches where the baseline wins. Nothing
          is trimmed to flatter the model.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">Market picks</div>
        <p>
          Sportsbooks price some of the matches the model predicts. For
          those, the locked probability is compared with the captured
          price. EV is the locked probability times the decimal price,
          minus one. Positive means the price looked too generous against
          the model's view.
        </p>
        <p>
          The de-vig column strips the bookmaker's margin with Shin's
          method to show a fair probability. When more than one book
          priced a match, the pick takes the best captured price and names
          the book. Closing line value compares the entry price to the
          same book's closing price.
        </p>
        <p>
          All of it stays labeled unvalidated until a preregistered number
          of picks has graded, a threshold set before the first pick and
          never moved. Map totals are excluded from EV for now because
          their probabilities carry a measured bias. None of this is
          betting advice. It is a measurement of the model.
        </p>
      </div>
      <div className="panel">
        <div className="panel-title">The honesty rules</div>
        <p>
          A few rules hold everything together. Numbers are computed by
          scripts from stored data, never typed in. Evaluation is
          chronological only, with no peeking at the future, and the test
          window is read once. Findings that make the model look bad stay
          on record instead of being patched away.
        </p>
        <p>
          The code, the assumptions, and the bug log are public.{" "}
          <a className="linklike"
             href="https://github.com/ArminObar/valorant-predictor"
             target="_blank" rel="noreferrer">Read the source on GitHub.</a>
        </p>
      </div>
    </div>
  );
}
